version: "3.9"

services:
  minitwit:
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: ${DOCKER_USERNAME}/minitwitimage
    environment:
      GO_ENV: production
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: minitwit
    networks:
      - database-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - database-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres

volumes:
  postgres-db:
    driver: local

networks:
  database-network:
    name: database-network
