version: "3.9"

services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    environment:
      GO_ENV: production
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: minitwit
    networks:
      - database-network
      - prometheus-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - database-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - prometheus-network
      - monitoring
    volumes:
      - prometheus-data:/prometheus
      - type: bind
        source: ./monitoring/prometheus.yml
        target: /prometheus/prometheus.yml
        read_only: true
    restart: unless-stopped
    command:
      - "--config.file=prometheus.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - prometheus-network
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitoring

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    volumes:
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.2.0"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - elk
    ports:
      - "5601:5601"

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    command:
      - "-e"
      - "--strict.perms=false"
    volumes:
      - ./logging/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

volumes:
  postgres-db:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  elk_elasticsearch_data:
    driver: local

networks:
  database-network:
    name: database-network
  prometheus-network:
    name: prometheus-network
  elk:
    name: elk
  monitoring:
    driver: bridge
