version: "3.9"

services:
  minitwit:
    #image: ${DOCKER_USERNAME}/minitwitimage
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitwit
    networks:
      - database-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - database-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
      - ./tools/schema_postgres.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-db:
    driver: local

networks:
  database-network:
    name: database-network
