name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      #Checkout repository files
      - name: Checkout
        uses: actions/checkout@v2
      #Run linter to check if new code follows the style guidelines
      - name: lint
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      # Run go unit tests
      - name: Unit testing
        run: |
          go test -v ./...
      # Run simulator integration tests
      - name: Simulator tests
        run: |
          pip install -r ./test/requirements.txt
          pytest ./test/test_sim_compliance.py
      # Run end-to-end tests through Selenium
      - name: Selenium tests
        run: |
          sudo apt install firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
          tar xzvf geckodriver-v0.32.0-linux64.tar.gz
          mv geckodriver ./test
          rm geckodriver-v0.32.0-linux64.tar.gz
          pytest ./test/test_itu_minitwit_ui.py
