name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      #Checkout repository files
      - name: Checkout
        uses: actions/checkout@v2
      #Run linter to check if new code follows the style guidelines
      - name: lint
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      # Run go unit tests
      - name: Unit testing
        run: |
          go test -v ./...
      # Run simulator integration tests
      - name: Simulator tests
        run: |
          pip install -r ./tools/requirements.txt
          pytest ./tools/test_sim_compliance.py
